//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities1 : DbContext
    {
        public DBEntities1()
            : base("name=DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Claim> Claims { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Motorbike> Motorbikes { get; set; }

        public System.Data.Entity.DbSet<InsuranceProject.ViewModel.ClaimModel> ClaimModels { get; set; }

        public System.Data.Entity.DbSet<InsuranceProject.ViewModel.ClientModel> ClientModels { get; set; }

        public System.Data.Entity.DbSet<InsuranceProject.ViewModel.ContactModel> ContactModels { get; set; }
    }
}
